### ISSUE TITLE
reload/unload command always expands to configdir

### ISSUE THREAD

**Issue by TingPing** [mniip/hexchat-lua#5]
As mentioned on IRC the plugin window calls these commands and the loaded script could be anywhere.

**Comment by mniip** [comment]
To me it seems that hexchat is at fault in this case. The plugin tells hexchat the exact filename of the script, and then hexchat asks to unload a script without providing the exact filename. What if there are multiple scripts with that filename in different directories?

**Comment by TingPing** [comment]
I agree, will look into fixing that.
