### ISSUE TITLE
Weird emit_print behavior

### ISSUE THREAD

**Issue by TingPing** [mniip/hexchat-lua#8]
``` lua
hexchat.hook_print('Channel Message', function (args)
    print('this is printed once')
    hexchat.emit_print('Fake event', 'nothing', 'should happen')
    return hexchat.EAT_ALL
end)
```

In this example the print happens twice for me, I have encountered other weird issues such as the return not getting registered, I imagine that function is corrupting the stack or something.

**Comment by TingPing** [comment]
Similar corruption seems to happen on `context:print()` also... weird issues in [this script](https://github.com/TingPing/plugins/blob/master/HexChat/highlight.lua) where the value of `channel` could be changed.

**Comment by mniip** [comment]
As discussed on IRC, this couldn't be reproduced, so closing for now.
